{
 "title": "Pizza Dashboard",
 "description": "Pizza pizza",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP requests by method/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "requests_GET_total", "legendFormat": "__auto" },
    { "expr": "requests_POST_total", "legendFormat": "__auto" },
    { "expr": "requests_PUT_total", "legendFormat": "__auto" },
    { "expr": "requests_DELETE_total", "legendFormat": "__auto" },
    { "expr": "rate(requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "active_users_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "successful_total", "legendFormat": "__auto" },
    { "expr": "failed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU and memory usage percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_percent", "legendFormat": "__auto" },
    { "expr": "memory_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizzas Sold/Minute & Creation Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "pizza_creation_failures_per_minute_total",
     "legendFormat": "__auto"
    },
    { "expr": "pizzas_sold_per_minute_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenue_per_minute_currency_total[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(request_time_GET_milliseconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "pizza_creation_latency_milliseconds_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}